import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-expect-error - the server build file is generated by `remix vite:build`
import * as build from "../build/server";

// Type for the Pages Function event context
interface PagesEventContext {
  request: Request;
  env: Record<string, unknown>;
  params: Record<string, string>;
  waitUntil: (promise: Promise<unknown>) => void;
  passThroughOnException: () => void;
  next: (input?: Request | string, init?: RequestInit) => Promise<Response>;
  data: Record<string, unknown>;
  functionPath: string;
}

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (args) => {
    // The args structure from createPagesFunctionHandler
    // args.context is the EventContext from Pages Functions
    // args.request is the Request
    const eventContext = args.context as unknown as PagesEventContext;
    
    // In Cloudflare Pages Functions, env is directly on the event context
    // But createPagesFunctionHandler might wrap it differently
    // Let's try multiple approaches
    
    // Approach 1: Direct from args.context.env (standard)
    let env = (args.context as any)?.env;
    
    // Approach 2: Maybe it's on args directly
    if (!env || Object.keys(env).length === 0) {
      env = (args as any)?.env;
    }
    
    // Approach 3: Check if args has a different structure
    if (!env || Object.keys(env).length === 0) {
      // Log for debugging
      console.log("[Pages Function] args keys:", Object.keys(args));
      console.log("[Pages Function] args.context type:", typeof args.context);
      if (args.context) {
        console.log("[Pages Function] args.context keys:", Object.keys(args.context));
      }
    }
    
    return {
      cloudflare: {
        env: env || {},
        cf: (args.context as any)?.cf,
        ctx: args.context,
      },
    };
  },
  mode: process.env.NODE_ENV,
});
