import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-expect-error - the server build file is generated by `remix vite:build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (args) => {
    // Access env from the Pages Function context
    // Try args.context.env first, then args.env as fallback
    const env = (args.context as any)?.env || (args as any)?.env || {};
    
    return {
      cloudflare: {
        env,
        cf: (args.context as any)?.cf,
        ctx: args.context,
      },
    };
  },
  mode: process.env.NODE_ENV,
});
