// Generated by wrangler, do not edit manually
interface Env {
  // R2 Storage
  CONTENT_BUCKET: R2Bucket;
  
  // Site Configuration
  SITE_NAME: string;
  
  // R2 Configuration (for display/external access)
  R2_BUCKET_NAME?: string;
  R2_PUBLIC_URL?: string;
  R2_ACCOUNT_ID?: string;
  
  // Admin Authentication
  ADMIN_USERNAME?: string;
  ADMIN_PASSWORD?: string;
  
  // Image Optimization
  IMAGE_CDN_URL?: string;
  IMAGE_PROVIDER?: "cloudflare" | "sharp" | "none";
}
